line = 1
polygon = 1
triangle = 1
quad = 1
tetra = 1
hexahedron = 1
wedge = 1
pyramid = 1
line3 = 2
triangle6 = 2
quad9 = 2
tetra10 = 2
hexahedron27 = 2
wedge18 = 2
pyramid14 = 2
vertex = 0
quad8 = 2
hexahedron20 = 2
triangle10 = 3
triangle15 = 4
triangle21 = 5
line4 = 3
line5 = 4
line6 = 5
tetra20 = 3
tetra35 = 4
tetra56 = 5
quad16 = 3
quad25 = 4
quad36 = 5
triangle28 = 6
triangle36 = 7
triangle45 = 8
triangle55 = 9
triangle66 = 10
quad49 = 6
quad64 = 7
quad81 = 8
quad100 = 9
quad121 = 10
line7 = 6
line8 = 7
line9 = 8
line10 = 9
line11 = 10
tetra84 = 6
tetra120 = 7
tetra165 = 8
tetra220 = 9
tetra286 = 10
wedge40 = 4
wedge75 = 5
hexahedron64 = 4
hexahedron125 = 5
hexahedron216 = 6
hexahedron343 = 7
hexahedron512 = 8
hexahedron729 = 9
hexahedron1000 = 10
wedge126 = 6
wedge196 = 7
wedge288 = 8
wedge405 = 9
wedge550 = 10
VTK_LAGRANGE_CURVE = 1
VTK_LAGRANGE_TRIANGLE = 1
VTK_LAGRANGE_QUADRILATERAL = 1
VTK_LAGRANGE_TETRAHEDRON = 1
VTK_LAGRANGE_HEXAHEDRON = 1
VTK_LAGRANGE_WEDGE = 1
VTK_LAGRANGE_PYRAMID = 1
